services:
  server:
    image: mars1836/backend_toeic:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    volumes:
      - ./keys:/app/keys
      - ./env:/app/.env
      - ./uploads:/app/src/uploads
    restart: always
  nginx:
    image: mars1836/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./backup:/backup
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
volumes:
  mongo_data:
  redis_data:
