services:
  server:
    image: mars1836/backend_toeic:latest
    container_name: backend_toeic
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    environment:
      - AUTH_SECRET=toeic-journey
    volumes:
      - ./keys:/app/keys
      - ./env:/app/.env
      - ./uploads:/app/src/uploads
      - ./uploads:/app/dist/uploads
    restart: always
    networks:
      - toeic_network

  backup:
    image: toeic-prep-backup
    container_name: backup_toeic
    restart: always
    networks:
      - toeic_network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - toeic_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./backup1:/backup1
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - toeic_network
volumes:
  mongo_data:
  redis_data:
networks:
  toeic_network:
    driver: bridge
